### ISSUE TITLE
01_Linear_Models Exercise 4 MSE or SSE?

### ISSUE THREAD

**Issue by kungfujam** [CSTR-Edinburgh/mlpractical#18]
Equation (5) shows *sum* of squared errors:

    (5) $
    E = \frac{1}{2} \sum_{n=1}^N ||\mathbf{y}^n - \mathbf{t}^n||^2 =  \sum_{n=1}^N E^n \\
      E^n = \frac{1}{2} ||\mathbf{y}^n - \mathbf{t}^n||^2
    $

Text states it is the *mean* squared error. It's implemented as the mean squared error in the solutions to exercise below.

**Comment by pswietojanski** [comment]
Thanks, will add normalising factor to the equation later so it stays cohesive with text (though, it's just for monitoring purposes anyway and both would be correct).

**Comment by pswietojanski** [comment]
And, the reason I left like this were further equations in which I did not want to carry the normaliser through -- since equations (8)-(10)  are actually computing the sum of errors (which we wanted to be implemented in this form in Ex 4 and Ex 5) and then per-example contribution (mean) is taken into account at the very end by adjusting learning rate. I should have been more explicit about this perhaps. Hope, you will find tutorials 02 onwards clearer in many respects.

**Comment by kungfujam** [comment]
Grand, cheers for the explanation. For context, I did much of this material last year on a previous Masters; I'm trying to think of things from the perspective of newbies.

I created a pull request to clarify some earlier stuff; I'm spelling stuff out and suggesting some notational consistency. I think it's quite useful to use upper case variables to indicate matrices *or* **N** (i.e. nr data points) dimensional vectors. See what you think and disregard if this is not consistent with latter exercises.
