### ISSUE TITLE
Conflict between miniconda and anaconda

### ISSUE THREAD

**Issue by pligor** [CSTR-Edinburgh/mlpractical#41]
I suppose someone who has setup anaconda already at his or her system could easily use that instead of miniconda?

This must be clarified to prevent from others bringing their system in an unstable state where both applications are installed

The important difference is that the `env_vars.sh` files are created inside anaconda folder (same path)

Also a clarification that the path for the `MLP_DATA_DIR` is hard coded and therefore must customized according to the system is not a bad idea

Let me know if there are any issues with using anaconda. Thank you

**Comment by matt-graham** [comment]
Hi,

Thanks for the comments.

> I suppose someone who has setup anaconda already at his or her system could easily use that instead of miniconda?
>
> This must be clarified to prevent from others bringing their system in an unstable state where both applications are installed

The set up instructions do currently state that it's okay to use Anaconda instead of Miniconda (just above 'Installing Miniconda' section). I don't think there is any reason you couldn't install Miniconda alongside Anaconda (though you would probably want to not have it added to `PATH` by default), though if you already have Anaconda installed there would be no real advantage.

> Also a clarification that the path for the MLP_DATA_DIR is hard coded and therefore must customized according to the system is not a bad idea

The current instructions for setting up the `MLP_DATA_DIR` environment variable do state they only apply if you've the default Miniconda install location of `~/miniconda2` and cloned the mlpractical repository to `~/mlpractical`.

As a general comment, the instructions are designed for working with DICE with the idea that you should also be able use them as a starting point to install to a personal machine on a different system but that you will need to tweak things according to your local set up. Setting up a Git issue like this to share experiences about getting set up on other platforms is a good idea, but generally we won't be officially supporting other systems as the set up instructions are already quite long and we don't want to make them any more complicated.
